version: '3'

services:
  reverse-proxy:
    image: traefik:1.7.16
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
  app:
    container_name: app-nextcloud
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
    volumes:
      - ./nextcloud:/var/www/html
      - /media/raid1/nextcloud:/var/www/html/data
    expose:
      - '80'
      - '9000'
  onlyoffice-document-server:
    container_name: app-onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  nginx:
    container_name: app-nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nextcloud:/var/www/html
    ports:
      - 7800:80
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:MY.HOST.NAME"
      - "traefik.port=80"
      - "traefik.docker.network=web"
  db:
    container_name: app-mariadb
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT_PASSWORD
      - MYSQL_PASSWORD=PASSWORD
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud
    ports:
      - 3306
    networks:
      - onlyoffice

networks:
  onlyoffice:
    driver: 'bridge'
  web:
    external: true

volumes:
  document_data:
  document_log:
  mysql_data:
